platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: gemfire-spring

outputs:
  - name: image

params:
  CONTEXT: gemfire-spring/gemfire-backend
  DOCKERFILE: gemfire-spring/gemfire-backend/Dockerfile

run:
  path: build
