---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 6.9.1-jdk11-alpine

inputs:
  - name: gemfire-spring

run:
  path: "/bin/sh"
  args: ["gradle", "cleanTest", "test"]
