platform: linux

image_resource: gradle-image

inputs:
  - name: gemfire-spring
  - name: gradle-image

caches:
  - path: $HOME/.gradle/caches/
  - path: $HOME/.gradle/wrapper/

run:
  path: "/bin/sh"
  args:
    - -c
    - |
      cd gemfire-spring/gemfire-backend
      gradle cleanTest test
