platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 6.9.1-jdk11-alpine

inputs:
  - name: gemfire-spring

caches:
  - path: $HOME/.gradle/caches/
  - path: $HOME/.gradle/wrapper/

run:
  path: "/bin/sh"
  args:
    - -c
    - |
      cd gemfire-spring/gemfire-backend
      gradle cleanTest test
