apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie-deployment
  name: movie-deployment
  namespace: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-deployment
    spec:
      containers:
        - image: guyzsarun/gemfire-springboot:latest
          name: gemfire-springboot
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
          envFrom:
            - configMapRef:
                name: movie-config
            - secretRef:
                name: movie-secret
