apiVersion: v1
data:
  SPRING_DATA_GEMFIRE_MANAGEMENT_HTTP_HOST: tanzu-gemfire-cluster-locator-0.tanzu-gemfire-cluster-locator.gemfire-cluster
  SPRING_DATA_GEMFIRE_POOL_LOCATORS: tanzu-gemfire-cluster-locator-0.tanzu-gemfire-cluster-locator.gemfire-cluster[10334]
kind: ConfigMap
metadata:
  name: movie-config
  namespace: movie
